apiVersion: v1
kind: Secret
metadata:
  name: quickbite-secrets
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-secret" | base64
  # In production, these should be managed by a secret management system
  DB_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # 'postgrespassword'
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==  # 'redispassword'
  JWT_SECRET: anNvbndlYnRva2VuLXNlY3JldC1rZXktZm9yLXF1aWNrYml0ZQ==  # 'jsonwebtoken-secret-key-for-quickbite'
  STRIPE_API_KEY: c2tfdGVzdF95b3VyLXRlc3Qtc3RyaXBlLWtleQ==  # 'sk_test_your-test-stripe-key'